### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by MarkSwanson** [akamai/AkamaiOPEN-edgegrid-python#26]
$ [sudo] pip install edgegrid-python --upgrade

Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-7t0hME-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cffi
Storing debug log for failure in /home/maswanso/.pip/pip.log

I tried with/without sudo and with/without --upgrade.
It failed on a Mac (python 2.7.10) and on Ubuntu 14.04 (python 2.7.6).

**Comment by kmteoh** [comment]
I had issue mentioned above but on win10 with python 3.6.0, and my fix was:

- run 'easy_install pip'
- then run 'pip install --upgrade setuptools'
- then run  'pip install edgegrid-python'

and it seems happy after...

**Comment by robertolopezlopez** [comment]
Hi @MarkSwanson ,

I have just tried to reproduce your problem on a clean new docker container `python:2.7.10` with the following commands:


```
$ docker container run -it --rm python:2.7.10 /bin/bash
root@bf54dc64fc06:/# pip install edgegrid-python --upgrade
Collecting edgegrid-python
...
    Complete output from command python setup.py egg_info:

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-WKXweJ/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ImportError: No module named setuptools_rust

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-WKXweJ/cryptography
You are using pip version 7.1.2, however version 21.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@bf54dc64fc06:/# pip install --upgrade 'pip<21.0'
Collecting pip<21.0
...
Successfully installed pip-20.3.4
You are using pip version 20.3.4, however version 21.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@bf54dc64fc06:/# pip install edgegrid-python --upgrade
...
Successfully installed certifi-2020.12.5 cffi-1.14.5 chardet-4.0.0 cryptography-3.3.2 edgegrid-python-1.1.1 enum34-1.1.10 idna-2.10 ipaddress-1.0.23 ndg-httpsclient-0.5.1 pyOpenSSL-20.0.1 pyasn1-0.4.8 pycparser-2.20 requests-2.25.1 six-1.16.0 urllib3-1.26.5
root@bf54dc64fc06:/#
```

Could you please once again try to reproduce on your side and let us know? Thanks.

**Comment by MarkSwanson** [comment]
I'm no longer working on this. Since it seems to work for you I'll close this.

**Comment by robertolopezlopez** [comment]
thanks @MarkSwanson
