### ISSUE TITLE
Asynchronous http calls

### ISSUE THREAD

**Issue by vreddhi** [akamai/AkamaiOPEN-edgegrid-python#27]
This isnt an issue, rather a question. Can we use aiohttp instead of requests library to support asynchronous http calls ?

**Comment by kentaro0919** [comment]
I think you can make it work with http://aiohttp.readthedocs.io/en/stable/client.html

**Comment by robertolopezlopez** [comment]
Thank you for your question @vreddhi , I will close it at this point :-)
