### ISSUE TITLE
There is no explicit indication anywhere obvious whether this package supports both python2 and python3

### ISSUE THREAD

**Issue by vitaly-krugl** [akamai/AkamaiOPEN-edgegrid-python#37]
Please add an explicit indication whether this package supports both python2 and python3. Ideally, this should be reflected in the `classifiers` parameter when your setup.py is calling `setuptools.setup()` (see https://packaging.python.org/guides/distributing-packages-using-setuptools/#classifiers and https://pypi.org/classifiers/).  For example:

```
setup(
    ...
    classifiers=[
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7'
    ]
)
```

Also, it wouldn't hurt to add specific, enforceable, supported python versions into `python_requires`, for example:
```
    # Require Python 2.7.10+ or Python 3 starting with 3.7 (per PEP-440)
    python_requires='>=2.7.10, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, '
                    '!=3.5.*, !=3.6.*, <4',
```

**Comment by robertolopezlopez** [comment]
Thank you @vitaly-krugl ,

We have addressed this issue in our internal repository and soon it will be released.

Regards

**Comment by robertolopezlopez** [comment]
Hi @vitaly-krugl ,

This issue has been addressed in our [latest](https://pypi.org/project/edgegrid-python/1.2.0/) [release](https://github.com/akamai/AkamaiOPEN-edgegrid-python/releases/tag/v1.2.0). Thank you for bringing up this topic.

Regards,

Roberto
