### ISSUE TITLE
Does not work with PyOpenSSL from Mac OSX

### ISSUE THREAD

**Issue by elreydetodo** [akamai/AkamaiOPEN-edgegrid-python#41]
The version of pyOpenSSL included in base Mac OSX is incompatible with this library. As a result, users of [egcurl](https://github.com/akamai/AkamaiOPEN-edgegrid-python/) get a misleading error message when they they try to run that script.

The version included with OSX is 0.13.1, which [was released back in 2013](https://pypi.org/project/pyOpenSSL/#history). I am not sure what minimum version we really need, but I propose to set the minimum version in `requirements.txt` to 17.0.0, which was released in August 2017. The current version is 19.0.0, and we could reasonably pick that one too if we wanted.

It's worth noting that I think we only need this library if the user is using Python 2.7. There are some if statements that only import it if the Python major version is less than 3. Since Python 3 is more than 10 years old now it'd really be nice if Apple would upgrade their base Python version...

In the mean time, Mac OS users can upgrade their local pyOpenSSL version with this command:

```
pip install -U pyOpenSSL
```

Note that this is NOT run with `sudo` - that's _very_ important. The `-U` argument instructs `pip` to install it into the user's home directory. You CANNOT successfully replace the system version of pyOpenSSL. The command will fail.

**Comment by robertolopezlopez** [comment]
Closing after after our chat. Thank you, @elreydetodo

**Comment by robertolopezlopez** [comment]
This will be done in next release

**Comment by robertolopezlopez** [comment]
Hi @elreydetodo,

Thanks for creating this ticket, it has been addressed in our [latest release](https://pypi.org/project/edgegrid-python/1.2.0/).

Regards

Roberto
