### ISSUE TITLE
Python3.8 section not recognize

### ISSUE THREAD

**Issue by anthonyxpalermo** [akamai/AkamaiOPEN-edgegrid-python#48]
It appears that in Python 3.8 the module is not recognizing the sections ?

MacOS 10.15

cat ~/.edgerc 
[default]
client_secret = the-client-secret
host = secretlocation.luna.akamaiapis.net
access_token = the-access-token
client_token = the-client-token

>>> section = 'default'
>>> baseurl = 'https://%s' % edgerc.get(section, 'host')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'default'

**Comment by robertolopezlopez** [comment]
Hi @anthonyxpalermo ,

Thank you for raising this issue. We have already fixed this issue in our internal repository, we will release the fix as soon as we can :-)

As a temporary solution, please do not use the `~` character when instantiating `EdgeRc` - instead, use the full path to  to your `.edgerc`

Regards

**Comment by robertolopezlopez** [comment]
Hi @anthonyxpalermo,

Thank you for creating this issue, it has been fixed in our [latest release](https://pypi.org/project/edgegrid-python/1.2.0/).

Regards,

Roberto
