### ISSUE TITLE
Default Section not recognized: python 3.8.2

### ISSUE THREAD

**Issue by psybersonik** [akamai/AkamaiOPEN-edgegrid-python#50]
I am unable to parse the contents of the **default** section successfully.
The .edgerc file is readable by the CLI and HTTPie
This seems to be an issue similar to [https://github.com/akamai/AkamaiOPEN-edgegrid-python/issues/48](url)

**Error message:**
 % /Applications/Xcode.app/Contents/Developer/usr/bin/python3 "/Users/_redacted_/Apps/edge.py"
Traceback (most recent call last):
  File "/Users/_redacted_/Apps/edge.py", line 6, in <module>
    baseurl = 'https://%s' % edgerc.get(section, 'host')
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'default'

**The edge.py file(renamed to .txt) is as attached.**

[edge.txt](https://github.com/akamai/AkamaiOPEN-edgegrid-python/files/5571046/edge.txt)

**Comment by robertolopezlopez** [comment]
Hi @psybersonik ,

Thank you for raising this issue. We have already fixed this issue in our internal repository, we will release the fix as soon as we can :-)

As a temporary solution, please replace `~/.edgerc` with the full path to your `.edgerc`

Regards

**Comment by robertolopezlopez** [comment]
Hi @psybersonik,

Thank you for creating this issue, it has been fixed in our [latest release](https://pypi.org/project/edgegrid-python/1.2.0/).

Regards,

Roberto
