### ISSUE TITLE
.edgerc not found after installing httpie-edgegrid in windows

### ISSUE THREAD

**Issue by Nesi05** [akamai/AkamaiOPEN-edgegrid-python#53]
I have installed the  httpie-edgegrid from the github link provided in Akamai documentation. After running the setup.py file in a Linux (ubuntu) environment I have set up in my PC, the **.edgerc** file, which supposed to be generated in my home Desktop is no where to be found.

Therefore I cannot setup my credentials.
Any solution or alternative would be much appreciated.

**Comment by robertolopezlopez** [comment]
Hi @Nesi05,

You may find a template in [`AkamaiOPEN-edgegrid-python/akamai/edgegrid/test/sample_edgerc`](https://github.com/akamai/AkamaiOPEN-edgegrid-python/blob/master/akamai/edgegrid/test/sample_edgerc). Please, let us know if that fit your needs.

Regards,

Roberto

**Comment by robertolopezlopez** [comment]
In our next release, we will give a clearer explanation about how to create an .edgerc file. Thank you for opening this issue, @Nesi05
