### ISSUE TITLE
Command failing even after updating pyOpenSSL

### ISSUE THREAD

**Issue by hmrocketuser** [akamai/AkamaiOPEN-edgegrid-python#62]
While trying to execute commands using below, i am stilling see errors.

**http --auth-type edgegrid -a default: :/diagnostic-tools/v2/ghost-locations/available**

My edgerc file exists in ~/.edgerc
Tried below as well pip3 install --ignore-installed pyOpenSSL but still no luck, can you explain why is this failing?

http --auth-type edgegrid -a default: :/diagnostic-tools/v2/ghost-locations/available 
usage:
    http [--auth-type {basic,bearer,digest}] [METHOD] URL [REQUEST_ITEM ...]

error:
    argument --auth-type/-A: invalid choice: 'edgegrid' (choose from 'basic', 'bearer', 'digest')

for more information:
    run 'http --help' or visit https://httpie.io/docs/cli

**Comment by robertolopezlopez** [comment]
@hmrocketuser : thanks for creating this issue (and closing it)

Post-mortem: this error has nothing to do with edgegrid-python, rather with httpie-edgegrid. According to your error, it is not properly installed. As you may have noticed already, it was not properly installed in your system.
